export const CANCEL_FOOD_DATA = 'CANCEL_FOOD_DATA'
export const FETCH_FOOD_DATA = 'FETCH_FOOD_DATA'
export const FETCH_FOOD_DATA_FULLFILLED = 'FETCH_FOOD_DATA_FULLFILLED'
export const FETCH_FOOD_DATA_FAILED = 'FETCH_FOOD_DATA_FAILED'
